# Generated by Django 3.2.6 on 2021-09-07 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('employee_address', models.CharField(max_length=100)),
                ('employee_name', models.CharField(max_length=50)),
                ('employee_number', models.IntegerField()),
                ('employee_college', models.CharField(max_length=50)),
                ('employee_department', models.CharField(max_length=30)),
            ],
        ),
    ]
