# Generated by Django 3.2.6 on 2021-09-23 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiseapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_email', models.CharField(max_length=100)),
                ('student_address', models.CharField(max_length=150)),
                ('student_mobile', models.IntegerField(default=0)),
                ('student_project_type', models.CharField(max_length=10)),
                ('student_project_name', models.CharField(max_length=100)),
                ('student_project_code', models.IntegerField()),
                ('student_project_fees', models.IntegerField()),
                ('student_project_pending_fees', models.IntegerField(default=0)),
                ('student_project_payment_mode', models.CharField(default='Online', max_length=30)),
                ('student_date_of_payment', models.DateField()),
            ],
        ),
    ]
