# Generated by Django 3.2.6 on 2021-10-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiseapp', '0002_datastudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastudent',
            name='student_mobile',
            field=models.BigIntegerField(default=0),
        ),
    ]
